dist: xenial
language: python # 默认是ruby
python: 
  - "3.7"

install:
  # nuo主题需要extended版本的hugo，其他主题可以用最新的普通版本就行
  - wget https://github.com/gohugoio/hugo/releases/download/v0.82.1/hugo_extended_0.82.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - hugo -D

# 构建完成后会自动更新Github Pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public